---
# TODO: fedora only
- name: Install GNOME pinentry
  become: true
  ansible.builtin.dnf:
    name: pinentry-gnome3

- name: Ensure gnupg directory exists
  ansible.builtin.file:
    path: "{{ target_home }}/.gnupg"
    state: directory
    mode: "0700"

- name: Configure gpg-agent to use GNOME pinentry
  ansible.builtin.copy:
    dest: "{{ target_home }}/.gnupg/gpg-agent.conf"
    mode: "0600"
    content: |
      pinentry-program /usr/bin/pinentry-gnome3
