---
# TODO: fedora only
- name: Set terminal font
  block:
    - name: Disable system font
      community.general.dconf:
        key: /org/gnome/Ptyxis/use-system-font
        value: "false"
    - name: Set new font
      community.general.dconf:
        key: /org/gnome/Ptyxis/font-name
        value: "'FiraCode Nerd Font Mono 16'"

- name: Set terminal theme
  block:
    - name: Set default profile
      community.general.dconf:
        key: /org/gnome/Ptyxis/default-profile-uuid
        value: "'00000000-0000-0000-0000-000000000001'"
    - name: Register profile
      community.general.dconf:
        key: /org/gnome/Ptyxis/profile-uuids
        value: "['00000000-0000-0000-0000-000000000001']"
    - name: Set nord theme on profile
      community.general.dconf:
        key: /org/gnome/Ptyxis/Profiles/00000000-0000-0000-0000-000000000001/palette
        value: "'nord'"

- name: Turn off terminal audible bell
  community.general.dconf:
    key: /org/gnome/Ptyxis/audible-bell
    value: "false"

- name: Turn off terminal visual bell
  community.general.dconf:
    key: /org/gnome/Ptyxis/visual-bell
    value: "false"
