---
# TODO: fedora only
- name: Install Syncthing
  become: true
  ansible.builtin.dnf:
    name: syncthing

- name: Enable and start Syncthing service
  become: true
  ansible.builtin.service:
    name: "syncthing@{{ target_user }}"
    enabled: true
    state: started
