---
name: lint

on:
  push:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14.6"
      - name: Install linter
        run: pip install ansible-lint
      - name: Install collections
        run: ansible-galaxy collection install -r requirements.yaml
      - name: Lint
        run: ansible-lint
