---
- name: Set git user name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ full_name }}"

- name: Set git user email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ email }}"

- name: Set git signing key
  community.general.git_config:
    name: user.signingkey
    scope: global
    value: "{{ signing_key }}"

- name: Enable commit signing
  community.general.git_config:
    name: commit.gpgsign
    scope: global
    value: "true"

- name: Set git default branch
  community.general.git_config:
    name: init.defaultbranch
    scope: global
    value: main
