---
- name: Set timezone
  become: true
  community.general.timezone:
    name: "{{ timezone }}"

# TODO: fedora only
- name: Install locale langpacks
  become: true
  ansible.builtin.dnf:
    name:
      - "glibc-langpack-{{ default_locale.split('_')[0] }}"
      - "glibc-langpack-{{ regional_locale.split('_')[0] }}"

- name: Configure locale
  become: true
  ansible.builtin.copy:
    dest: /etc/locale.conf
    mode: "0644"
    content: |
      LANG={{ default_locale }}
      LC_TIME={{ regional_locale }}
      LC_NUMERIC={{ regional_locale }}
      LC_MONETARY={{ regional_locale }}
      LC_PAPER={{ regional_locale }}
      LC_MEASUREMENT={{ regional_locale }}
