---
- name: Upgrade all packages
  become: true
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: true

- name: Install base utilities
  become: true
  ansible.builtin.dnf:
    name:
      - bat
      - curl
      - git
      - gnupg2
      - nano
      - ncdu
      - tmux
      - tree
      - wget

- name: Install Ansible module dependencies
  become: true
  ansible.builtin.dnf:
    name: python3-psutil

- name: Configure locale
  ansible.builtin.import_tasks: locale.yml

- name: Configure fish
  ansible.builtin.import_tasks: fish.yml

- name: Configure git
  ansible.builtin.import_tasks: git.yml

- name: Configure passwordless sudo
  ansible.builtin.import_tasks: sudo.yml
