---
- name: Assert that target_user is the connecting user
  ansible.builtin.assert:
    that: target_user == ansible_facts['user_id']
    fail_msg: "target_user is '{{ target_user }}', but this play connects as '{{ ansible_facts['user_id'] }}'."
    quiet: true

- name: Assert that the connecting user is not root
  ansible.builtin.assert:
    that: ansible_facts['user_id'] != "root"
    fail_msg: "This play connects as root, but it configures a normal user account. Connect as an existing user."
    quiet: true

# TODO: fedora only
- name: Upgrade packages
  become: true
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: true


# TODO: fedora only
- name: Install base utilities
  become: true
  ansible.builtin.package:
    name:
      - bat
      - curl
      - git
      - gnupg2
      - nano
      - ncdu
      - tmux
      - tree
      - wget

# TODO: fedora only
- name: Install Ansible module dependencies
  become: true
  ansible.builtin.package:
    name:
      - python3-dnf # TODO: https://github.com/ansible-collections/community.general/issues/12501
      - python3-psutil

- name: Configure locale
  ansible.builtin.import_tasks: locale.yml

- name: Setup fish
  ansible.builtin.import_tasks: fish.yml

- name: Setup git
  ansible.builtin.import_tasks: git.yml

- name: Setup passwordless sudo
  ansible.builtin.import_tasks: sudo.yml
