---
- name: Install base utilities
  become: true
  ansible.builtin.dnf:
    name:
      - bat
      - curl
      - git
      - gnupg2
      - nano
      - ncdu
      - tmux
      - tree
      - wget

- name: Install Ansible module dependencies
  become: true
  ansible.builtin.dnf:
    name: python3-psutil

- name: Configure locale
  ansible.builtin.import_tasks: locale.yaml

- name: Configure fish
  ansible.builtin.import_tasks: fish.yaml

- name: Configure git
  ansible.builtin.import_tasks: git.yaml

- name: Configure passwordless sudo
  ansible.builtin.import_tasks: sudo.yaml
