---
all:
  hosts:
    vm:
      ansible_connection: local
  children:
    workstation:
      hosts:
        vm:
    desktop_gnome:
      hosts:
        vm:
    development:
      hosts:
        vm:
    gaming:
      hosts:
        vm:
