---
- name: Base configuration
  hosts: all
  roles:
    - common

- name: Workstation profile
  hosts: workstation
  roles:
    - workstation

- name: Development profile
  hosts: development
  roles:
    - development
