---
- name: Base configuration
  hosts: all
  pre_tasks:
    - name: Run preflight checks
      ansible.builtin.import_role:
        name: preflight
  roles:
    - common

- name: Workstation profile
  hosts: workstation
  roles:
    - workstation

- name: Development profile
  hosts: development
  roles:
    - development
