---
name: ansible

on:
  push:
    paths:
      - "ansible/**"
      - ".github/workflows/ansible.yaml"
  pull_request:
    paths:
      - "ansible/**"
      - ".github/workflows/ansible.yaml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.14.6"
      - name: Install linter
        run: pip install ansible-lint
      - name: Install collections
        run: ansible-galaxy collection install -r requirements.yaml
      - name: Lint
        run: ansible-lint
