---
- name: Ensure backgrounds directory exists
  ansible.builtin.file:
    path: "{{ target_home }}/.local/share/backgrounds"
    state: directory
    mode: "0755"

- name: Install wallpaper
  ansible.builtin.copy:
    src: wallpaper.png
    dest: "{{ target_home }}/.local/share/backgrounds/fedora.png"
    mode: "0644"

- name: Install user avatar
  ansible.builtin.copy:
    src: avatar.png
    dest: "{{ target_home }}/.face"
    mode: "0644"

- name: Install AccountsService avatar
  become: true
  ansible.builtin.copy:
    src: avatar.png
    dest: "/var/lib/AccountsService/icons/{{ target_user }}"
    mode: "0644"

- name: Set AccountsService avatar path
  become: true
  community.general.ini_file:
    path: "/var/lib/AccountsService/users/{{ target_user }}"
    section: User
    option: Icon
    value: "/var/lib/AccountsService/icons/{{ target_user }}"
    mode: "0600"
    create: true
