---
# TODO: fedora only
- name: Remove excluded GNOME packages
  become: true
  ignore_errors: true  # noqa: ignore-errors some packages may not be present
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: absent
  loop: "{{ gnome_removed_packages }}"

- name: Autoremove orphan dependencies
  become: true
  ansible.builtin.dnf:
    autoremove: true
