---
- name: Remove installer leftover packages
  become: true
  ignore_errors: true  # noqa: ignore-errors some packages may not be present
  ansible.builtin.dnf:
    name: "{{ gnome_removed_installer_packages }}"
    state: absent

- name: Remove default GNOME app packages
  become: true
  ignore_errors: true  # noqa: ignore-errors some packages may not be present
  ansible.builtin.dnf:
    name: "{{ gnome_removed_default_apps }}"
    state: absent

- name: Remove crash reporting packages
  become: true
  ignore_errors: true  # noqa: ignore-errors some packages may not be present
  ansible.builtin.dnf:
    name: "{{ gnome_removed_crash_reporting_packages }}"
    state: absent

- name: Remove browser packages
  become: true
  ignore_errors: true  # noqa: ignore-errors some packages may not be present
  ansible.builtin.dnf:
    name: "{{ gnome_removed_browser_packages }}"
    state: absent

- name: Gather installed package facts
  ansible.builtin.package_facts:

- name: Remove native LibreOffice packages
  become: true
  ansible.builtin.dnf:
    name: "{{ ansible_facts.packages.keys() | select('match', '^(libreoffice|unoconv)') | list }}"
    state: absent
  when: ansible_facts.packages.keys() | select('match', '^(libreoffice|unoconv)') | list | length > 0

- name: Autoremove orphan dependencies
  become: true
  ansible.builtin.dnf:
    autoremove: true
