---
- name: Configure GNOME desktop
  ansible.builtin.import_tasks: desktop.yaml

- name: Remove GNOME desktop bloat
  ansible.builtin.import_tasks: cleanup.yaml

- name: Install GNOME desktop applications
  become: true
  ansible.builtin.dnf:
    name:
      - gnome-tweaks
      - baobab
      - dconf-editor
      - decibels
      - deja-dup
      - gnome-calculator
      - gnome-connections
      - gnome-disk-utility
      - gnome-font-viewer
      - gnome-logs
      - gnome-system-monitor
      - gnome-text-editor
      - loupe
      - nautilus
      - papers
      - showtime
      - snapshot
      - seahorse
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list
      - gnome-shell-extension-gsconnect

- name: Configure GNOME settings
  ansible.builtin.import_tasks: settings.yaml

- name: Configure GNOME appearance
  ansible.builtin.import_tasks: appearance.yaml
